const express = require('express');
const authRoutes = require('./authRoutes');
const transactionRoutes = require('./transactionRoutes');
const categoryRoutes = require('./categoryRoutes');
const tagRoutes = require('./tagRoutes');
const transportRoutes = require('./transportRoutes');
const budgetRoutes = require('./budgetRoutes');
const notificationRoutes = require('./notificationRoutes');
const reminderRoutes = require('./reminderRoutes');
const calendarRoutes = require('./calendarRoutes');
const debtRoutes = require('./debtRoutes');
const expenseSplitRoutes = require('./expenseSplitRoutes');
const metaRoutes = require('./metaRoutes');
const moedaRoutes = require('./moedaRoutes');
const viagemRoutes = require('./viagemRoutes');
const grupoRoutes = require('./grupoRoutes');
const purchasePlanningRoutes = require('./purchasePlanningRoutes');
const cronRoutes = require('./cronRoutes');
const syncRoutes = require('./syncRoutes');
const dashboardRoutes = require('./dashboardRoutes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/transacoes', transactionRoutes);
router.use('/categorias', categoryRoutes);
router.use('/tags', tagRoutes);
router.use('/transporte', transportRoutes);
router.use('/orcamentos', budgetRoutes);
router.use('/notificacoes', notificationRoutes);
router.use('/lembretes', reminderRoutes);
router.use('/calendario', calendarRoutes);
router.use('/dividas', debtRoutes);
router.use('/divisoes', expenseSplitRoutes);
router.use('/metas', metaRoutes);
router.use('/moedas', moedaRoutes);
router.use('/viagens', viagemRoutes);
router.use('/grupos', grupoRoutes);
router.use('/planejamento-compra', purchasePlanningRoutes);
router.use('/cron', cronRoutes);
router.use('/sync', syncRoutes);
router.use('/dashboard', dashboardRoutes);

module.exports = router;
