/** Preços base ida/volta estimados (referência GRU) por hub IATA */
const TRIP_AIRPORT_HUB_FALLBACK_BRL = {
    GRU: 450,
    GIG: 650,
    CNF: 480,
    VIX: 520,
    BSB: 490,
    SSA: 560,
    REC: 590,
    FOR: 620,
    CWB: 420,
    POA: 500,
    FLN: 460,
    MAO: 780,
    NAT: 600,
    GYN: 510,
    VCP: 430,
    BEL: 720,
    MCZ: 580,
    JPA: 590,
    AJU: 620,
    UDI: 480,
    RAO: 470,
    CGB: 550,
    CGR: 520,
    IGU: 540,
    LDB: 490,
    JOI: 480,
    NVT: 470,
    THE: 680,
    SLZ: 650,
    IMP: 720,
    PMW: 580,
    PVH: 880,
    RBR: 920,
    BVB: 950,
    MCP: 900,
    STM: 750,
    JDO: 640,
    PNZ: 620,
    XAP: 500,
    JJD: 680,
    IOS: 640,
};

/** Metadados por país (internacional) */
const TRIP_COUNTRY_META = {
    BR: { countryName: 'Brasil', moedaSugerida: 'BRL' },
    AR: { countryName: 'Argentina', moedaSugerida: 'ARS' },
    UY: { countryName: 'Uruguai', moedaSugerida: 'UYU' },
    PY: { countryName: 'Paraguai', moedaSugerida: 'PYG' },
    CL: { countryName: 'Chile', moedaSugerida: 'CLP' },
    PE: { countryName: 'Peru', moedaSugerida: 'PEN' },
    CO: { countryName: 'Colômbia', moedaSugerida: 'COP' },
    MX: { countryName: 'México', moedaSugerida: 'MXN' },
    US: { countryName: 'Estados Unidos', moedaSugerida: 'USD' },
    CA: { countryName: 'Canadá', moedaSugerida: 'CAD' },
    PT: { countryName: 'Portugal', moedaSugerida: 'EUR' },
    ES: { countryName: 'Espanha', moedaSugerida: 'EUR' },
    FR: { countryName: 'França', moedaSugerida: 'EUR' },
    IT: { countryName: 'Itália', moedaSugerida: 'EUR' },
    GB: { countryName: 'Reino Unido', moedaSugerida: 'GBP' },
    DE: { countryName: 'Alemanha', moedaSugerida: 'EUR' },
    NL: { countryName: 'Holanda', moedaSugerida: 'EUR' },
    BE: { countryName: 'Bélgica', moedaSugerida: 'EUR' },
    CH: { countryName: 'Suíça', moedaSugerida: 'CHF' },
    AT: { countryName: 'Áustria', moedaSugerida: 'EUR' },
    IE: { countryName: 'Irlanda', moedaSugerida: 'EUR' },
    GR: { countryName: 'Grécia', moedaSugerida: 'EUR' },
    TR: { countryName: 'Turquia', moedaSugerida: 'TRY' },
    JP: { countryName: 'Japão', moedaSugerida: 'JPY' },
    KR: { countryName: 'Coreia do Sul', moedaSugerida: 'KRW' },
    CN: { countryName: 'China', moedaSugerida: 'CNY' },
    TH: { countryName: 'Tailândia', moedaSugerida: 'THB' },
    IN: { countryName: 'Índia', moedaSugerida: 'INR' },
    AU: { countryName: 'Austrália', moedaSugerida: 'AUD' },
    NZ: { countryName: 'Nova Zelândia', moedaSugerida: 'NZD' },
    AE: { countryName: 'Emirados Árabes', moedaSugerida: 'AED' },
    QA: { countryName: 'Catar', moedaSugerida: 'QAR' },
    MA: { countryName: 'Marrocos', moedaSugerida: 'MAD' },
    ZA: { countryName: 'África do Sul', moedaSugerida: 'ZAR' },
    EG: { countryName: 'Egito', moedaSugerida: 'EGP' },
    IL: { countryName: 'Israel', moedaSugerida: 'ILS' },
    SG: { countryName: 'Singapura', moedaSugerida: 'SGD' },
    MY: { countryName: 'Malásia', moedaSugerida: 'MYR' },
    ID: { countryName: 'Indonésia', moedaSugerida: 'IDR' },
    PH: { countryName: 'Filipinas', moedaSugerida: 'PHP' },
    VN: { countryName: 'Vietnã', moedaSugerida: 'VND' },
    CR: { countryName: 'Costa Rica', moedaSugerida: 'CRC' },
    PA: { countryName: 'Panamá', moedaSugerida: 'USD' },
    CU: { countryName: 'Cuba', moedaSugerida: 'CUP' },
    DO: { countryName: 'República Dominicana', moedaSugerida: 'DOP' },
    PR: { countryName: 'Porto Rico', moedaSugerida: 'USD' },
    EC: { countryName: 'Equador', moedaSugerida: 'USD' },
    BO: { countryName: 'Bolívia', moedaSugerida: 'BOB' },
    VE: { countryName: 'Venezuela', moedaSugerida: 'USD' },
    NO: { countryName: 'Noruega', moedaSugerida: 'NOK' },
    SE: { countryName: 'Suécia', moedaSugerida: 'SEK' },
    DK: { countryName: 'Dinamarca', moedaSugerida: 'DKK' },
    FI: { countryName: 'Finlândia', moedaSugerida: 'EUR' },
    PL: { countryName: 'Polônia', moedaSugerida: 'PLN' },
    CZ: { countryName: 'República Tcheca', moedaSugerida: 'CZK' },
    HU: { countryName: 'Hungria', moedaSugerida: 'HUF' },
    HR: { countryName: 'Croácia', moedaSugerida: 'EUR' },
    RS: { countryName: 'Sérvia', moedaSugerida: 'RSD' },
    RU: { countryName: 'Rússia', moedaSugerida: 'RUB' },
    KE: { countryName: 'Quênia', moedaSugerida: 'KES' },
    TZ: { countryName: 'Tanzânia', moedaSugerida: 'TZS' },
    HK: { countryName: 'Hong Kong', moedaSugerida: 'HKD' },
    TW: { countryName: 'Taiwan', moedaSugerida: 'TWD' },
};

/** Preços internacionais base por hub IATA (referência GRU) */
const TRIP_INTL_HUB_FALLBACK_BRL = {
    EZE: 1900,
    MVD: 1700,
    ASU: 1650,
    SCL: 2100,
    LIM: 2400,
    BOG: 2600,
    MEX: 3200,
    CUN: 3400,
    GDL: 3100,
    MIA: 3400,
    JFK: 3800,
    EWR: 3800,
    LAX: 4200,
    SFO: 4500,
    ORD: 4000,
    LAS: 3900,
    BOS: 4100,
    SEA: 4300,
    YYZ: 4200,
    YVR: 4500,
    LIS: 3800,
    OPO: 3900,
    MAD: 4100,
    BCN: 4200,
    CDG: 4300,
    NCE: 4400,
    FCO: 4500,
    MXP: 4400,
    VCE: 4500,
    LHR: 4600,
    MAN: 4700,
    FRA: 4400,
    MUC: 4500,
    BER: 4400,
    AMS: 4300,
    BRU: 4300,
    ZRH: 4600,
    VIE: 4400,
    ATH: 4500,
    IST: 4200,
    NRT: 6200,
    HND: 6200,
    ICN: 5800,
    PVG: 5600,
    PEK: 5500,
    HKG: 5400,
    TPE: 5600,
    BKK: 5200,
    DEL: 5400,
    BOM: 5500,
    SYD: 7800,
    MEL: 7900,
    AKL: 8200,
    DXB: 4900,
    DOH: 5000,
    AUH: 5100,
    SIN: 5800,
    KUL: 5600,
    DPS: 6200,
    JKT: 6000,
    MNL: 5900,
    HAN: 5800,
    SGN: 5700,
    RAK: 4700,
    CPT: 5100,
    JNB: 5200,
    CAI: 4800,
    TLV: 4900,
    HNL: 7500,
    PTY: 3600,
    SJO: 3500,
    HAV: 3400,
    SJU: 3300,
    UIO: 3200,
    CPH: 4500,
    ARN: 4600,
    OSL: 4700,
    HEL: 4600,
    PRG: 4300,
    BUD: 4200,
    WAW: 4400,
    SVO: 4800,
    NBO: 5500,
    ZNZ: 5800,
};

function getHubFallbackBrl(iata, { international = false } = {}) {
    const map = international ? TRIP_INTL_HUB_FALLBACK_BRL : TRIP_AIRPORT_HUB_FALLBACK_BRL;
    return map[iata] ?? (international ? 4500 : 550);
}

function getCountryMeta(countryCode) {
    return (
        TRIP_COUNTRY_META[String(countryCode ?? '').toUpperCase()] ?? {
            countryName: 'Internacional',
            moedaSugerida: 'USD',
        }
    );
}

module.exports = {
    TRIP_AIRPORT_HUB_FALLBACK_BRL,
    TRIP_INTL_HUB_FALLBACK_BRL,
    TRIP_COUNTRY_META,
    getHubFallbackBrl,
    getCountryMeta,
};
