export const CURRENCY_FLAG_CODES = {
  AED: 'ae',
  AFN: 'af',
  ANG: 'cw',
  ARS: 'ar',
  AUD: 'au',
  BHD: 'bh',
  BOB: 'bo',
  BRL: 'br',
  BYN: 'by',
  CAD: 'ca',
  CHF: 'ch',
  CLP: 'cl',
  CNY: 'cn',
  COP: 'co',
  CRC: 'cr',
  CZK: 'cz',
  DKK: 'dk',
  EGP: 'eg',
  EUR: 'eu',
  FJD: 'fj',
  GBP: 'gb',
  GEL: 'ge',
  GHS: 'gh',
  HKD: 'hk',
  HUF: 'hu',
  IDR: 'id',
  ILS: 'il',
  INR: 'in',
  IQD: 'iq',
  IRR: 'ir',
  JOD: 'jo',
  JPY: 'jp',
  KES: 'ke',
  KRW: 'kr',
  KWD: 'kw',
  KYD: 'ky',
  MAD: 'ma',
  MXN: 'mx',
  MYR: 'my',
  NIO: 'ni',
  NOK: 'no',
  NZD: 'nz',
  PEN: 'pe',
  PHP: 'ph',
  PLN: 'pl',
  PYG: 'py',
  RON: 'ro',
  RSD: 'rs',
  RUB: 'ru',
  SAR: 'sa',
  SDG: 'sd',
  SEK: 'se',
  SGD: 'sg',
  SYP: 'sy',
  THB: 'th',
  TRY: 'tr',
  TWD: 'tw',
  UAH: 'ua',
  USD: 'us',
  UYU: 'uy',
  VEF: 've',
  VND: 'vn',
  XAG: 'un',
  XAU: 'un',
  XCD: 'ag',
  XOF: 'sn',
  XPF: 'pf',
  ZAR: 'za',
}

export function getCurrencyFlagCode(code) {
  return CURRENCY_FLAG_CODES[String(code ?? '').toUpperCase()] ?? null
}

export function getCurrencyFlagUrl(code) {
  const flagCode = getCurrencyFlagCode(code)
  if (!flagCode) return null
  return `https://hatscripts.github.io/circle-flags/flags/${flagCode}.svg`
}
