import {
  Anchor,
  Baby,
  Backpack,
  Banknote,
  Bed,
  Bike,
  BookMarked,
  BookOpen,
  Bot,
  Briefcase,
  Brush,
  Building2,
  Bus,
  Cake,
  Camera,
  Car,
  ChefHat,
  Church,
  Clapperboard,
  Cloud,
  Code,
  Coffee,
  Coins,
  Compass,
  CreditCard,
  Crown,
  Droplets,
  Dumbbell,
  Fish,
  Flag,
  FlaskConical,
  Flower2,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Hammer,
  HandCoins,
  Headphones,
  Heart,
  Home,
  IceCream,
  Key,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Luggage,
  MapPin,
  Medal,
  Mic,
  Monitor,
  Music,
  Package,
  Paintbrush,
  Palette,
  Palmtree,
  PawPrint,
  PenTool,
  PiggyBank,
  Pill,
  Plane,
  Printer,
  Receipt,
  Rocket,
  Sailboat,
  Scissors,
  Server,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Target,
  Tent,
  Ticket,
  Train,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  UtensilsCrossed,
  Wallet,
  Watch,
  Waves,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react'

/**
 * Regras de ícone por nome da meta (ordem importa: a primeira que bater vence).
 * Palavras são comparadas sem acento e em minúsculas.
 */
export const GOAL_ICON_RULES = [
  // ── Viagens e lazer ─────────────────────────────────────────
  {
    icon: Plane,
    keywords: [
      'viagem',
      'viajar',
      'trip',
      'ferias',
      'férias',
      'passagem',
      'aereo',
      'aéreo',
      'aviao',
      'avião',
      'voo',
      'turismo',
      'cruzeiro',
      'disney',
      'europa',
      'exterior',
      'nordeste',
      'macae',
      'macaé',
      'rio de janeiro',
      'sao paulo',
      'são paulo',
      'paris',
      'londres',
      'nova york',
      'orlando',
      'miami',
      'cancun',
      'cancún',
      'argentina',
      'chile',
      'portugal',
      'espanha',
      'italia',
      'itália',
      'japao',
      'japão',
      'intercambio',
      'intercâmbio',
      'exchange',
      'aeroporto',
    ],
  },
  {
    icon: Palmtree,
    keywords: [
      'praia',
      'caribe',
      'havai',
      'havaí',
      'resort',
      'tropical',
      'paraty',
      'buzios',
      'búzios',
      'florianopolis',
      'florianópolis',
      'salvador',
      'fortaleza',
      'recife',
      'maceio',
      'maceió',
      'jericoacoara',
      'fernando de noronha',
    ],
  },
  {
    icon: Globe,
    keywords: ['mundo', 'global', 'internacional', 'exterior', 'passaporte', 'visto'],
  },
  {
    icon: MapPin,
    keywords: ['destino', 'roteiro', 'city tour', 'passeio', 'conhecer'],
  },
  {
    icon: Compass,
    keywords: ['aventura', 'explorar', 'expedicao', 'expedição', 'mochileiro'],
  },
  {
    icon: Tent,
    keywords: [
      'camping',
      'acampamento',
      'trilha',
      'trekking',
      'montanha',
      'serra',
      'chapada',
      'refugio',
      'refúgio',
      'ecoturismo',
    ],
  },
  {
    icon: Backpack,
    keywords: ['mochila', 'mala', 'bagagem', 'hostel', 'airbnb'],
  },
  {
    icon: Luggage,
    keywords: ['malas', 'valise', 'viagem curta'],
  },
  {
    icon: Ship,
    keywords: ['barco', 'iate', 'lancha', 'navegar', 'maritimo', 'marítimo', 'transatlantico'],
  },
  {
    icon: Sailboat,
    keywords: ['veleiro', 'regata', 'vela'],
  },
  {
    icon: Anchor,
    keywords: ['porto', 'marina', 'costeira'],
  },
  {
    icon: Train,
    keywords: ['trem', 'metro', 'ferrovia', 'subway', 'tram'],
  },
  {
    icon: Bus,
    keywords: ['onibus', 'ônibus', 'van', 'transporte coletivo', 'fretamento'],
  },
  {
    icon: Ticket,
    keywords: ['ingresso', 'ingressos', 'show', 'evento', 'festival', 'parque tematico', 'parque temático'],
  },
  {
    icon: Clapperboard,
    keywords: ['cinema', 'filme', 'serie', 'série', 'netflix', 'streaming', 'pipoca', 'sessao', 'sessão'],
  },
  {
    icon: Waves,
    keywords: ['surf', 'mergulho', 'lago', 'rio', 'kayak', 'stand up'],
  },
  {
    icon: Fish,
    keywords: ['pesca', 'aquario', 'aquário', 'peixe'],
  },
  {
    icon: Snowflake,
    keywords: ['ski', 'neve', 'inverno', 'chile ski', 'gramado inverno'],
  },
  {
    icon: Sun,
    keywords: ['verao', 'verão', 'sol', 'piscina', 'veraneio'],
  },
  {
    icon: Umbrella,
    keywords: ['chuva', 'guarda chuva', 'temporada'],
  },

  // ── Veículos ────────────────────────────────────────────────
  {
    icon: Car,
    keywords: [
      'carro',
      'carro novo',
      'automove',
      'automóvel',
      'veiculo',
      'veículo',
      'caminhonete',
      'pickup',
      'suv',
      'hatch',
      'sedan',
      'ipva',
      'cnh',
      'habilitacao',
      'habilitação',
      'uber',
      '99',
      'estacionamento',
      'garagem',
      'pneu',
      'oficina carro',
    ],
  },
  {
    icon: Truck,
    keywords: ['caminhao', 'caminhão', 'truck', 'mudanca', 'mudança'],
  },
  {
    icon: Bike,
    keywords: [
      'moto',
      'motocicleta',
      'motoca',
      'scooter',
      'bicicleta',
      'bike',
      'patinete',
      'ebike',
      'e-bike',
    ],
  },

  // ── Moradia ─────────────────────────────────────────────────
  {
    icon: Home,
    keywords: [
      'casa',
      'imovel',
      'imóvel',
      'apartamento',
      'ap',
      'moradia',
      'entrada da casa',
      'casa propria',
      'casa própria',
      'aluguel',
      'reforma',
      'construcao',
      'construção',
      'obra',
      'terreno',
      'financiamento imobiliario',
      'financiamento imobiliário',
      'condominio',
      'condomínio',
      'kitnet',
      'studio',
      'sobrado',
      'chacara',
      'chácara',
      'sitio',
      'sítio',
      'fazenda',
    ],
  },
  {
    icon: Building2,
    keywords: ['predio', 'prédio', 'edificio', 'edifício', 'comercial', 'sala comercial'],
  },
  {
    icon: Key,
    keywords: ['chave', 'entrada imovel', 'entrada imóvel', 'escritura'],
  },
  {
    icon: Hammer,
    keywords: ['demolicao', 'demolição', 'ampliacao', 'ampliação'],
  },
  {
    icon: Wrench,
    keywords: ['reparo', 'manutencao', 'manutenção', 'conserto', 'oficina', 'encanador', 'eletricista'],
  },
  {
    icon: Sofa,
    keywords: ['moveis', 'móveis', 'sofa', 'sofá', 'sala', 'decoracao', 'decoração'],
  },
  {
    icon: Bed,
    keywords: ['quarto', 'cama', 'colchao', 'colchão', 'enxoval'],
  },
  {
    icon: Droplets,
    keywords: ['agua', 'água', 'hidraulica', 'hidráulica', 'banheiro', 'chuveiro'],
  },
  {
    icon: Zap,
    keywords: ['energia', 'eletrica', 'elétrica', 'painel solar', 'gerador'],
  },
  {
    icon: TreePine,
    keywords: ['jardim', 'paisagismo', 'quintal', 'arvore', 'árvore'],
  },

  // ── Educação ────────────────────────────────────────────────
  {
    icon: GraduationCap,
    keywords: [
      'faculdade',
      'universidade',
      'graduacao',
      'graduação',
      'pos',
      'pós',
      'mba',
      'mestrado',
      'doutorado',
      'vestibular',
      'enem',
      'diploma',
      'formatura',
      'medicina',
      'direito',
      'engenharia',
      'tecnologo',
      'tecnólogo',
    ],
  },
  {
    icon: BookOpen,
    keywords: [
      'curso',
      'estudo',
      'estudar',
      'aula',
      'escola',
      'colegio',
      'colégio',
      'material escolar',
      'livro',
      'leitura',
      'certificacao',
      'certificação',
      'idioma',
      'ingles',
      'inglês',
      'espanhol',
      'frances',
      'francês',
      'alemao',
      'alemão',
      'mandarim',
      'japonês',
      'japones',
      'coreano',
      'preparatorio',
      'preparatório',
      'reforco',
      'reforço',
      'simulado',
      'prova',
      'concurso',
      'concurso publico',
      'concurso público',
    ],
  },
  {
    icon: BookMarked,
    keywords: ['biblioteca', 'e-book', 'kindle', 'apostila', 'leitura digital'],
  },
  {
    icon: FlaskConical,
    keywords: ['laboratorio', 'laboratório', 'quimica', 'química', 'biologia', 'pesquisa'],
  },
  {
    icon: PenTool,
    keywords: ['redacao', 'redação', 'escrita', 'dissertacao', 'dissertação', 'tcc', 'monografia'],
  },

  // ── Tecnologia ──────────────────────────────────────────────
  {
    icon: Laptop,
    keywords: [
      'notebook',
      'laptop',
      'computador',
      'pc',
      'macbook',
      'desktop',
      'setup',
      'workstation',
      'imac',
      'all in one',
    ],
  },
  {
    icon: Monitor,
    keywords: ['monitor', 'tela', 'periferico', 'periférico', 'teclado', 'mouse', 'webcam'],
  },
  {
    icon: Smartphone,
    keywords: [
      'celular',
      'smartphone',
      'iphone',
      'android',
      'tablet',
      'ipad',
      'telefone',
      'galaxy',
      'pixel',
      'smartwatch',
    ],
  },
  {
    icon: Watch,
    keywords: ['relogio inteligente', 'relógio inteligente', 'apple watch', 'garmin'],
  },
  {
    icon: Tv,
    keywords: ['tv', 'televisao', 'televisão', 'smart tv', 'home theater', 'projetor'],
  },
  {
    icon: Gamepad2,
    keywords: [
      'videogame',
      'video game',
      'playstation',
      'ps4',
      'ps5',
      'xbox',
      'nintendo',
      'switch',
      'steam',
      'jogo',
      'gamer',
      'pc gamer',
      'placa de video',
      'placa de vídeo',
      'gpu',
      'console',
    ],
  },
  {
    icon: Camera,
    keywords: [
      'camera',
      'câmera',
      'foto',
      'fotografia',
      'lente',
      'canon',
      'sony',
      'nikon',
      'gopro',
      'drone',
      'dji',
    ],
  },
  {
    icon: Headphones,
    keywords: ['fone', 'headphone', 'headset', 'airpods', 'audio', 'áudio', 'som'],
  },
  {
    icon: Printer,
    keywords: ['impressora', 'toner', 'papelaria'],
  },
  {
    icon: Server,
    keywords: ['servidor', 'nas', 'homelab', 'rack'],
  },
  {
    icon: Cloud,
    keywords: ['nuvem', 'backup', 'icloud', 'google drive', 'armazenamento'],
  },
  {
    icon: Wifi,
    keywords: ['internet', 'roteador', 'fibra', 'banda larga', 'modem'],
  },
  {
    icon: Code,
    keywords: [
      'programacao',
      'programação',
      'dev',
      'desenvolvedor',
      'software',
      'bootcamp',
      'fullstack',
      'frontend',
      'backend',
      'python',
      'javascript',
    ],
  },
  {
    icon: Bot,
    keywords: ['ia', 'inteligencia artificial', 'inteligência artificial', 'chatgpt', 'robotica', 'robótica', 'machine learning'],
  },

  // ── Arte, música e hobbies ──────────────────────────────────
  {
    icon: Music,
    keywords: [
      'musica',
      'música',
      'instrumento',
      'violao',
      'violão',
      'guitarra',
      'piano',
      'bateria',
      'show',
      'festival',
      'banda',
      'dj',
      'canto',
      'coral',
    ],
  },
  {
    icon: Mic,
    keywords: ['podcast', 'microfone', 'gravacao', 'gravação', 'estudio', 'estúdio'],
  },
  {
    icon: Palette,
    keywords: ['pintura', 'arte', 'tela', 'aquarela', 'oleo', 'óleo'],
  },
  {
    icon: Brush,
    keywords: ['desenho', 'ilustracao', 'ilustração', 'sketch', 'design grafico', 'design gráfico'],
  },
  {
    icon: Paintbrush,
    keywords: ['tatuagem', 'tattoo', 'piercing', 'body art'],
  },
  {
    icon: Scissors,
    keywords: ['cabelo', 'cabeleireiro', 'barbearia', 'salao', 'salão', 'manicure', 'estetica', 'estética'],
  },
  {
    icon: Sparkles,
    keywords: ['maquiagem', 'make', 'beleza', 'skincare', 'cosmetico', 'cosmético'],
  },
  {
    icon: Lightbulb,
    keywords: ['projeto pessoal', 'ideia', 'inovacao', 'inovação', 'criativo'],
  },

  // ── Família e celebrações ───────────────────────────────────
  {
    icon: Heart,
    keywords: [
      'casamento',
      'noivado',
      'lua de mel',
      'amor',
      'namoro',
      'alianca',
      'aliança',
      'festa de casamento',
      'wedding',
      'noiva',
      'noivo',
    ],
  },
  {
    icon: Church,
    keywords: ['igreja', 'batizado', 'crisma', 'cerimonia religiosa', 'cerimônia religiosa'],
  },
  {
    icon: Baby,
    keywords: [
      'bebe',
      'bebê',
      'filho',
      'filha',
      'gestante',
      'gravidez',
      'maternidade',
      'paternidade',
      'fralda',
      'berco',
      'berço',
      'parto',
      'enchoval bebe',
      'enchoval bebê',
      'chá de bebe',
      'chá de bebê',
    ],
  },
  {
    icon: Cake,
    keywords: [
      'aniversario',
      'aniversário',
      'festa',
      'bolo',
      'comemoracao',
      'comemoração',
      'cha de bebe',
      'chá de bebê',
      'cha de fraldas',
      'chá de fraldas',
      'cha revelacao',
      'chá revelação',
    ],
  },
  {
    icon: Gift,
    keywords: ['presente', 'gift', 'natal', 'pascoa', 'páscoa', 'dia das maes', 'dia das mães', 'dia dos pais'],
  },
  {
    icon: Flower2,
    keywords: ['flores', 'buque', 'buquê', 'arranjo', 'botanica', 'botânica'],
  },
  {
    icon: Crown,
    keywords: ['15 anos', 'debutante', 'coroacao', 'coroação', 'formatura baile'],
  },

  // ── Pets ────────────────────────────────────────────────────
  {
    icon: PawPrint,
    keywords: [
      'pet',
      'cachorro',
      'gato',
      'animal',
      'veterinario',
      'veterinário',
      'racao',
      'ração',
      'adocao',
      'adoção',
      'canil',
      'petshop',
      'pet shop',
      'aquario pet',
      'aquário pet',
      'hamster',
      'passaro',
      'pássaro',
    ],
  },

  // ── Saúde e bem-estar ───────────────────────────────────────
  {
    icon: Stethoscope,
    keywords: [
      'saude',
      'saúde',
      'medico',
      'médico',
      'consulta',
      'exame',
      'hospital',
      'plano de saude',
      'plano de saúde',
      'dentista',
      'ortodontia',
      'cirurgia',
      'psicologo',
      'psicólogo',
      'terapia',
      'fisioterapia',
      'nutricionista',
      'dermatologista',
      'oftalmologista',
      'checkup',
      'check-up',
    ],
  },
  {
    icon: Syringe,
    keywords: ['vacina', 'vacinacao', 'vacinação', 'imunizacao', 'imunização'],
  },
  {
    icon: Pill,
    keywords: ['remedio', 'remédio', 'medicamento', 'farmacia', 'farmácia', 'tratamento'],
  },
  {
    icon: Dumbbell,
    keywords: [
      'academia',
      'treino',
      'fitness',
      'musculacao',
      'musculação',
      'crossfit',
      'corrida',
      'maratona',
      'esporte',
      'futebol',
      'basquete',
      'volei',
      'vôlei',
      'natacao',
      'natação',
      'ciclismo',
      'yoga',
      'pilates',
      'personal',
      'suplemento',
      'whey',
    ],
  },
  {
    icon: Glasses,
    keywords: ['oculos grau', 'óculos grau', 'lente grau', 'otica', 'ótica'],
  },

  // ── Alimentação ─────────────────────────────────────────────
  {
    icon: UtensilsCrossed,
    keywords: [
      'restaurante',
      'jantar',
      'almoco',
      'almoço',
      'comida',
      'gastronomia',
      'chef',
      'delivery',
      'ifood',
      'rappi',
      'mercado',
      'feira',
      'supermercado',
    ],
  },
  {
    icon: ChefHat,
    keywords: ['cozinha', 'panela', 'airfryer', 'air fryer', 'utensilio cozinha', 'utensílio cozinha'],
  },
  {
    icon: Coffee,
    keywords: ['cafe', 'café', 'cafeteria', 'starbucks', 'nespresso', 'maquina de cafe', 'máquina de café'],
  },
  {
    icon: Wine,
    keywords: ['vinho', 'adega', 'espumante', 'champagne', 'champanhe', 'cachaca', 'cachaça'],
  },
  {
    icon: IceCream,
    keywords: ['sorvete', 'acai', 'açaí', 'doceria', 'confeitaria', 'sobremesa'],
  },

  // ── Compras e moda ──────────────────────────────────────────
  {
    icon: ShoppingBag,
    keywords: [
      'compras',
      'shopping',
      'loja',
      'roupa',
      'moda',
      'tenis',
      'tênis',
      'sapato',
      'bolsa',
      'relogio',
      'relógio',
      'joia',
      'joias',
      'oculos',
      'óculos',
      'vestido',
      'terno',
      'jaqueta',
      'casaco',
      'perfume',
      'cosmeticos',
      'cosméticos',
    ],
  },
  {
    icon: ShoppingCart,
    keywords: ['carrinho', 'ecommerce', 'e-commerce', 'shopee', 'mercado livre', 'amazon', 'shein'],
  },
  {
    icon: Store,
    keywords: ['loja fisica', 'loja física', 'franquia', 'quiosque', 'ponto comercial'],
  },
  {
    icon: Gem,
    keywords: ['diamante', 'ouro', 'prata', 'anel', 'brinco', 'colar', 'pulseira'],
  },

  // ── Trabalho e negócios ─────────────────────────────────────
  {
    icon: Briefcase,
    keywords: [
      'negocio',
      'negócio',
      'empresa',
      'startup',
      'freelance',
      'trabalho',
      'carreira',
      'escritorio',
      'escritório',
      'equipamento profissional',
      'home office',
      'cnpj',
      'mei',
      'sociedade',
      'parceria',
      'consultoria',
      'agencia',
      'agência',
    ],
  },
  {
    icon: Rocket,
    keywords: ['lancamento', 'lançamento', 'escalar', 'growth', 'mvp', 'produto digital'],
  },
  {
    icon: Trophy,
    keywords: ['premio', 'prêmio', 'conquista', 'campeonato', 'torneio', 'competicao', 'competição'],
  },
  {
    icon: Medal,
    keywords: ['medalha', 'reconhecimento', 'bonus', 'bônus', 'promocao', 'promoção'],
  },
  {
    icon: Flag,
    keywords: ['meta profissional', 'objetivo carreira', 'marco', 'milestone'],
  },

  // ── Finanças ────────────────────────────────────────────────
  {
    icon: TrendingUp,
    keywords: [
      'investimento',
      'investir',
      'acoes',
      'ações',
      'bolsa',
      'renda fixa',
      'tesouro',
      'fii',
      'cripto',
      'bitcoin',
      'ethereum',
      'aposentadoria',
      'independencia financeira',
      'independência financeira',
      'dividendos',
      'etf',
      'cdb',
      'lci',
      'lca',
      'fundos',
      'corretora',
      'day trade',
      'swing trade',
    ],
  },
  {
    icon: Landmark,
    keywords: ['banco', 'conta bancaria', 'conta bancária', 'abertura de conta', 'agencia bancaria', 'agência bancária'],
  },
  {
    icon: PiggyBank,
    keywords: [
      'reserva',
      'emergencia',
      'emergência',
      'poupanca',
      'poupança',
      'guardar dinheiro',
      'fundo',
      'colchao',
      'colchão',
      'reserva de emergencia',
      'reserva de emergência',
      'caixinha',
      'guardar',
    ],
  },
  {
    icon: Wallet,
    keywords: ['carteira', 'dinheiro', 'caixa', 'salario', 'salário', 'renda extra', 'mesada', 'grana'],
  },
  {
    icon: Coins,
    keywords: ['moeda', 'troco', 'poupanca curta', 'poupança curta'],
  },
  {
    icon: Banknote,
    keywords: ['nota', 'dinheiro vivo', 'especie', 'espécie', 'saque'],
  },
  {
    icon: CreditCard,
    keywords: [
      'cartao',
      'cartão',
      'credito',
      'crédito',
      'fatura',
      'limite',
      'anuidade',
      'milhas',
      'pontos',
      'black card',
    ],
  },
  {
    icon: HandCoins,
    keywords: ['emprestimo pessoal', 'empréstimo pessoal', 'emprestar', 'emprestei', 'juros'],
  },
  {
    icon: Receipt,
    keywords: [
      'imposto',
      'iptu',
      'ipva',
      'irpf',
      'declaracao',
      'declaração',
      'taxa',
      'multa',
      'boleto',
      'divida',
      'dívida',
      'quitar',
      'parcela',
      'financiamento',
      'consorcio',
      'consórcio',
      'carnê',
      'carne',
    ],
  },
  {
    icon: Shield,
    keywords: ['seguro', 'protecao', 'proteção', 'previdencia', 'previdência', 'cobertura', 'apolice', 'apólice'],
  },

  // ── Outros ──────────────────────────────────────────────────
  {
    icon: Package,
    keywords: ['encomenda', 'importacao', 'importação', 'frete', 'correios', 'sedex'],
  },
  {
    icon: Leaf,
    keywords: ['sustentavel', 'sustentável', 'eco', 'vegano', 'organico', 'orgânico', 'horta'],
  },
  {
    icon: Heart,
    keywords: ['doacao', 'doação', 'caridade', 'ong', 'voluntariado', 'solidariedade'],
  },
]

export function normalizeGoalName(nome) {
  return (nome ?? '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
}

function keywordMatches(normalized, keyword) {
  const term = normalizeGoalName(keyword)
  if (!term) return false

  if (term.includes(' ')) {
    return normalized.includes(term)
  }

  const pattern = new RegExp(`(?:^|[\\s,.;:!?()[\\]{}"'\\-/+])${term}(?:$|[\\s,.;:!?()[\\]{}"'\\-/+])`)
  return pattern.test(` ${normalized} `)
}

export function getGoalIcon(nome) {
  const normalized = normalizeGoalName(nome)
  if (!normalized) return Target

  for (const rule of GOAL_ICON_RULES) {
    const matched = rule.keywords.some((keyword) => keywordMatches(normalized, keyword))
    if (matched) return rule.icon
  }

  return Target
}
