import {
  Award,
  Banknote,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  Cake,
  Car,
  Cloud,
  CreditCard,
  Droplets,
  FileCheck,
  FileText,
  Flame,
  Globe,
  GraduationCap,
  HeartPulse,
  Home,
  Landmark,
  Lightbulb,
  Monitor,
  PawPrint,
  Percent,
  Phone,
  Pill,
  Plane,
  Receipt,
  RefreshCw,
  Repeat,
  Shield,
  Stethoscope,
  TrendingUp,
  Tv,
  Users,
  Wrench,
  Zap,
} from 'lucide-react'

export const REMINDER_CATEGORY_GROUPS = [
  {
    id: 'moradia',
    label: 'Moradia',
    values: ['ALUGUEL', 'CONDOMINIO', 'IPTU', 'SEGURO_RESIDENCIAL'],
  },
  {
    id: 'utilidades',
    label: 'Utilidades',
    values: ['LUZ', 'AGUA', 'GAS', 'INTERNET', 'TELEFONE', 'TV_ASSINATURA'],
  },
  {
    id: 'financeiro',
    label: 'Financeiro',
    values: [
      'FATURA_CARTAO',
      'EMPRESTIMO',
      'FINANCIAMENTO',
      'INVESTIMENTO',
      'IMPOSTO',
      'DECLARACAO_IR',
    ],
  },
  {
    id: 'veiculo',
    label: 'Veículo',
    values: ['IPVA', 'SEGURO_VEICULO', 'LICENCIAMENTO', 'REVISAO_VEICULO', 'MULTA'],
  },
  {
    id: 'saude',
    label: 'Saúde',
    values: ['PLANO_SAUDE', 'CONSULTA', 'EXAME', 'MEDICAMENTO', 'ACADEMIA'],
  },
  {
    id: 'educacao',
    label: 'Educação',
    values: ['MENSALIDADE_ESCOLA', 'MENSALIDADE_FACULDADE', 'CURSO', 'MATERIAL_ESCOLAR'],
  },
  {
    id: 'assinaturas',
    label: 'Assinaturas / Serviços',
    values: ['STREAMING', 'SOFTWARE', 'DOMINIO', 'HOSPEDAGEM', 'NUVEM'],
  },
  {
    id: 'pets',
    label: 'Pets',
    values: ['VACINA_PET', 'CONSULTA_PET', 'RACAO_PET'],
  },
  {
    id: 'trabalho',
    label: 'Trabalho / Negócios',
    values: [
      'NOTA_FISCAL',
      'FOLHA_PAGAMENTO',
      'CONTRATO',
      'RENOVACAO_CONTRATO',
      'CERTIDAO',
      'ALVARA',
    ],
  },
  {
    id: 'pessoal',
    label: 'Pessoal',
    values: ['ANIVERSARIO', 'REUNIAO', 'COMPROMISSO', 'VIAGEM', 'RENOVACAO_DOCUMENTO'],
  },
  {
    id: 'geral',
    label: 'Geral',
    values: ['RECORRENTE', 'PARCELAMENTO', 'OUTRO'],
  },
]

export const REMINDER_CATEGORY_LABELS = {
  ALUGUEL: 'Aluguel',
  CONDOMINIO: 'Condomínio',
  IPTU: 'IPTU',
  SEGURO_RESIDENCIAL: 'Seguro residencial',
  LUZ: 'Conta de luz',
  AGUA: 'Água',
  GAS: 'Gás',
  INTERNET: 'Internet',
  TELEFONE: 'Telefone',
  TV_ASSINATURA: 'TV / Assinatura',
  FATURA_CARTAO: 'Fatura do cartão',
  EMPRESTIMO: 'Empréstimo',
  FINANCIAMENTO: 'Financiamento',
  INVESTIMENTO: 'Investimento',
  IMPOSTO: 'Imposto',
  DECLARACAO_IR: 'Declaração IR',
  IPVA: 'IPVA',
  SEGURO_VEICULO: 'Seguro do veículo',
  LICENCIAMENTO: 'Licenciamento',
  REVISAO_VEICULO: 'Revisão do veículo',
  MULTA: 'Multa',
  PLANO_SAUDE: 'Plano de saúde',
  CONSULTA: 'Consulta',
  EXAME: 'Exame',
  MEDICAMENTO: 'Medicamento',
  ACADEMIA: 'Academia',
  MENSALIDADE_ESCOLA: 'Mensalidade escola',
  MENSALIDADE_FACULDADE: 'Mensalidade faculdade',
  CURSO: 'Curso',
  MATERIAL_ESCOLAR: 'Material escolar',
  STREAMING: 'Streaming',
  SOFTWARE: 'Software',
  DOMINIO: 'Domínio',
  HOSPEDAGEM: 'Hospedagem',
  NUVEM: 'Nuvem / Storage',
  VACINA_PET: 'Vacina pet',
  CONSULTA_PET: 'Consulta pet',
  RACAO_PET: 'Ração pet',
  NOTA_FISCAL: 'Nota fiscal',
  FOLHA_PAGAMENTO: 'Folha de pagamento',
  CONTRATO: 'Contrato',
  RENOVACAO_CONTRATO: 'Renovação de contrato',
  CERTIDAO: 'Certidão',
  ALVARA: 'Alvará',
  ANIVERSARIO: 'Aniversário',
  REUNIAO: 'Reunião',
  COMPROMISSO: 'Compromisso',
  VIAGEM: 'Viagem',
  RENOVACAO_DOCUMENTO: 'Renovação de documento',
  RECORRENTE: 'Recorrente',
  PARCELAMENTO: 'Parcelamento',
  OUTRO: 'Outro',
  FATURA: 'Fatura do cartão',
  MENSALIDADE: 'Mensalidade',
}

const REMINDER_CATEGORY_ICONS = {
  ALUGUEL: Home,
  CONDOMINIO: Building2,
  IPTU: Landmark,
  SEGURO_RESIDENCIAL: Shield,
  LUZ: Lightbulb,
  AGUA: Droplets,
  GAS: Flame,
  INTERNET: Globe,
  TELEFONE: Phone,
  TV_ASSINATURA: Tv,
  FATURA_CARTAO: CreditCard,
  EMPRESTIMO: Banknote,
  FINANCIAMENTO: Percent,
  INVESTIMENTO: TrendingUp,
  IMPOSTO: Receipt,
  DECLARACAO_IR: FileText,
  IPVA: Car,
  SEGURO_VEICULO: Shield,
  LICENCIAMENTO: FileCheck,
  REVISAO_VEICULO: Wrench,
  MULTA: Zap,
  PLANO_SAUDE: HeartPulse,
  CONSULTA: Stethoscope,
  EXAME: HeartPulse,
  MEDICAMENTO: Pill,
  ACADEMIA: Award,
  MENSALIDADE_ESCOLA: GraduationCap,
  MENSALIDADE_FACULDADE: GraduationCap,
  CURSO: BookOpen,
  MATERIAL_ESCOLAR: BookOpen,
  STREAMING: Monitor,
  SOFTWARE: Monitor,
  DOMINIO: Globe,
  HOSPEDAGEM: Cloud,
  NUVEM: Cloud,
  VACINA_PET: PawPrint,
  CONSULTA_PET: PawPrint,
  RACAO_PET: PawPrint,
  NOTA_FISCAL: Receipt,
  FOLHA_PAGAMENTO: Briefcase,
  CONTRATO: FileText,
  RENOVACAO_CONTRATO: RefreshCw,
  CERTIDAO: FileCheck,
  ALVARA: Building2,
  ANIVERSARIO: Cake,
  REUNIAO: Users,
  COMPROMISSO: Bell,
  VIAGEM: Plane,
  RENOVACAO_DOCUMENTO: FileCheck,
  RECORRENTE: Repeat,
  PARCELAMENTO: CreditCard,
  OUTRO: Box,
  FATURA: CreditCard,
  MENSALIDADE: GraduationCap,
}

const REMINDER_CATEGORY_COLORS = {
  ALUGUEL: '#F97316',
  CONDOMINIO: '#F97316',
  IPTU: '#64748B',
  SEGURO_RESIDENCIAL: '#3B82F6',
  LUZ: '#EAB308',
  AGUA: '#3B82F6',
  GAS: '#F97316',
  INTERNET: '#6366F1',
  TELEFONE: '#6366F1',
  TV_ASSINATURA: '#8B5CF6',
  FATURA_CARTAO: '#7C3AED',
  EMPRESTIMO: '#059669',
  FINANCIAMENTO: '#0EA5E9',
  INVESTIMENTO: '#10B981',
  IMPOSTO: '#EF4444',
  DECLARACAO_IR: '#EF4444',
  IPVA: '#64748B',
  SEGURO_VEICULO: '#3B82F6',
  LICENCIAMENTO: '#64748B',
  REVISAO_VEICULO: '#64748B',
  MULTA: '#EF4444',
  PLANO_SAUDE: '#EC4899',
  CONSULTA: '#EC4899',
  EXAME: '#EC4899',
  MEDICAMENTO: '#EC4899',
  ACADEMIA: '#10B981',
  MENSALIDADE_ESCOLA: '#10B981',
  MENSALIDADE_FACULDADE: '#10B981',
  CURSO: '#6366F1',
  MATERIAL_ESCOLAR: '#6366F1',
  STREAMING: '#8B5CF6',
  SOFTWARE: '#0EA5E9',
  DOMINIO: '#6366F1',
  HOSPEDAGEM: '#06B6D4',
  NUVEM: '#06B6D4',
  VACINA_PET: '#F97316',
  CONSULTA_PET: '#F97316',
  RACAO_PET: '#F97316',
  NOTA_FISCAL: '#475569',
  FOLHA_PAGAMENTO: '#475569',
  CONTRATO: '#475569',
  RENOVACAO_CONTRATO: '#475569',
  CERTIDAO: '#475569',
  ALVARA: '#475569',
  ANIVERSARIO: '#E11D48',
  REUNIAO: '#71717A',
  COMPROMISSO: '#71717A',
  VIAGEM: '#06B6D4',
  RENOVACAO_DOCUMENTO: '#71717A',
  RECORRENTE: '#7C3AED',
  PARCELAMENTO: '#7C3AED',
  OUTRO: '#71717A',
}

const LEGACY_CATEGORY_MAP = {
  FATURA: 'FATURA_CARTAO',
  MENSALIDADE: 'MENSALIDADE_FACULDADE',
}

export function normalizeReminderCategory(value) {
  if (!value) return 'OUTRO'
  const mapped = LEGACY_CATEGORY_MAP[value] ?? value
  return REMINDER_CATEGORY_LABELS[mapped] ? mapped : 'OUTRO'
}

export function getReminderCategoryMeta(categoria = 'OUTRO') {
  const normalized = normalizeReminderCategory(categoria)
  return {
    value: normalized,
    label: REMINDER_CATEGORY_LABELS[normalized] ?? 'Outro',
    icon: REMINDER_CATEGORY_ICONS[normalized] ?? Box,
    color: REMINDER_CATEGORY_COLORS[normalized] ?? '#71717A',
  }
}

export function ReminderCategoryIcon({
  categoria = 'OUTRO',
  size = 16,
  strokeWidth = 2,
  className,
}) {
  const meta = getReminderCategoryMeta(categoria)
  const Icon = meta.icon
  return <Icon size={size} strokeWidth={strokeWidth} className={className} />
}

export function buildReminderCategorySelectOptions() {
  return REMINDER_CATEGORY_GROUPS.flatMap((group) => [
    { value: `__group_${group.id}`, label: group.label, disabled: true },
    ...group.values.map((value) => {
      const meta = getReminderCategoryMeta(value)
      const Icon = meta.icon
      return {
        value,
        label: meta.label,
        icon: <Icon size={16} strokeWidth={2} />,
        iconColor: meta.color,
      }
    }),
  ])
}
