const IMAGE_SIZE = 'w=320&h=420&fit=crop&q=80'

const unsplash = (id) => `https://images.unsplash.com/photo-${id}?${IMAGE_SIZE}`

const wikimedia = (file) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=320`

function country(keywords, wikiTitles, image = null) {
  return { keywords, wikiTitles, image }
}

export const TRIP_COUNTRY_ENTRIES = [
  country(['afeganistao', 'afghanistan', 'af'], ['Afeganistão', 'Afghanistan']),
  country(['africa do sul', 'south africa', 'za'], ['África do Sul', 'South Africa'], wikimedia('Table_Mountain_Digital_Elevation_Model.jpg')),
  country(['albania', 'al'], ['Albânia', 'Albania']),
  country(['alemanha', 'germany', 'deutschland', 'de'], ['Alemanha', 'Germany'], unsplash('1560969184-10fe8719e047')),
  country(['andorra', 'ad'], ['Andorra']),
  country(['angola', 'ao'], ['Angola']),
  country(['antigua e barbuda', 'antigua', 'ag'], ['Antígua e Barbuda', 'Antigua and Barbuda']),
  country(['arabia saudita', 'saudi arabia', 'sa'], ['Arábia Saudita', 'Saudi Arabia']),
  country(['argelia', 'algeria', 'dz'], ['Argélia', 'Algeria']),
  country(['argentina', 'ar'], ['Argentina'], unsplash('1559827260-dc66d52bef19')),
  country(['armenia', 'am'], ['Armênia', 'Armenia']),
  country(['australia', 'australia', 'au'], ['Austrália', 'Australia'], unsplash('1506973035872-a19ec8bdb8df')),
  country(['austria', 'osterreich', 'at'], ['Áustria', 'Austria']),
  country(['azerbaijao', 'azerbaijan', 'az'], ['Azerbaijão', 'Azerbaijan']),
  country(['bahamas', 'bs'], ['Bahamas']),
  country(['bangladesh', 'bd'], ['Bangladesh']),
  country(['barbados', 'bb'], ['Barbados']),
  country(['bahrein', 'bahrain', 'bh'], ['Bahrein', 'Bahrain']),
  country(['belgica', 'belgium', 'be'], ['Bélgica', 'Belgium']),
  country(['belize', 'bz'], ['Belize']),
  country(['benin', 'bj'], ['Benim', 'Benin']),
  country(['bielorrussia', 'belarus', 'by'], ['Bielorrússia', 'Belarus']),
  country(['bolivia', 'bo'], ['Bolívia', 'Bolivia']),
  country(['bosnia', 'herzegovina', 'ba'], ['Bósnia e Herzegovina', 'Bosnia and Herzegovina']),
  country(['botsuana', 'botswana', 'bw'], ['Botsuana', 'Botswana']),
  country(['brasil', 'brazil', 'br'], ['Brasil', 'Brazil'], unsplash('1483729558449-99ef09a8c325')),
  country(['brunei', 'bn'], ['Brunei']),
  country(['bulgaria', 'bg'], ['Bulgária', 'Bulgaria']),
  country(['burkina faso', 'bf'], ['Burkina Faso']),
  country(['burundi', 'bi'], ['Burundi']),
  country(['butao', 'bhutan', 'bt'], ['Butão', 'Bhutan']),
  country(['cabo verde', 'cape verde', 'cv'], ['Cabo Verde', 'Cape Verde']),
  country(['camaroes', 'cameroon', 'cm'], ['Camarões', 'Cameroon']),
  country(['camboja', 'cambodia', 'kh'], ['Camboja', 'Cambodia']),
  country(['canada', 'ca'], ['Canadá', 'Canada'], unsplash('1519831353900-9a5817d4d633')),
  country(['catar', 'qatar', 'qa'], ['Catar', 'Qatar']),
  country(['cazaquistao', 'kazakhstan', 'kz'], ['Cazaquistão', 'Kazakhstan']),
  country(['chade', 'chad', 'td'], ['Chade', 'Chad']),
  country(['chile', 'cl'], ['Chile'], unsplash('1584489674699-c47f3310a485')),
  country(['china', 'cn'], ['China'], unsplash('1508804185872-d7badad00f7d')),
  country(['chipre', 'cyprus', 'cy'], ['Chipre', 'Cyprus']),
  country(['colombia', 'co'], ['Colômbia', 'Colombia'], unsplash('1568630860962-9d0f9f4b56c0')),
  country(['comores', 'comoros', 'km'], ['Comores', 'Comoros']),
  country(['congo', 'republica do congo', 'cg'], ['República do Congo', 'Republic of the Congo']),
  country(['coreia do norte', 'north korea', 'kp'], ['Coreia do Norte', 'North Korea']),
  country(['coreia do sul', 'south korea', 'korea', 'kr'], ['Coreia do Sul', 'South Korea'], unsplash('1517154429-39d7bd6ede51')),
  country(['costa do marfim', 'ivory coast', 'cote d ivoire', 'ci'], ['Costa do Marfim', 'Ivory Coast']),
  country(['costa rica', 'cr'], ['Costa Rica', 'Costa Rica']),
  country(['croacia', 'croatia', 'hr'], ['Croácia', 'Croatia']),
  country(['cuba', 'cu'], ['Cuba', 'Cuba']),
  country(['dinamarca', 'denmark', 'dk'], ['Dinamarca', 'Denmark']),
  country(['djibuti', 'djibouti', 'dj'], ['Djibuti', 'Djibouti']),
  country(['dominica', 'dm'], ['Dominica', 'Dominica']),
  country(['egito', 'egypt', 'eg'], ['Egito', 'Egypt'], unsplash('1572252009280-0fe5366e28ab')),
  country(['el salvador', 'sv'], ['El Salvador', 'El Salvador']),
  country(['emirados arabes', 'united arab emirates', 'uae', 'ae'], ['Emirados Árabes Unidos', 'United Arab Emirates'], unsplash('1512453979798-5ea266f8880c')),
  country(['equador', 'ecuador', 'ec'], ['Equador', 'Ecuador']),
  country(['eritreia', 'eritrea', 'er'], ['Eritreia', 'Eritrea']),
  country(['eslovaquia', 'slovakia', 'sk'], ['Eslováquia', 'Slovakia']),
  country(['eslovenia', 'slovenia', 'si'], ['Eslovênia', 'Slovenia']),
  country(['espanha', 'spain', 'es'], ['Espanha', 'Spain'], unsplash('1583422409516-2895a77efded')),
  country(['estados unidos', 'united states', 'usa', 'eua', 'us'], ['Estados Unidos', 'United States'], unsplash('1496442226666-8d4d0e62e6e9')),
  country(['estonia', 'ee'], ['Estónia', 'Estonia']),
  country(['etiopia', 'ethiopia', 'et'], ['Etiópia', 'Ethiopia']),
  country(['fiji', 'fj'], ['Fiji']),
  country(['filipinas', 'philippines', 'ph'], ['Filipinas', 'Philippines']),
  country(['finlandia', 'finland', 'fi'], ['Finlândia', 'Finland']),
  country(['franca', 'france', 'fr'], ['França', 'France'], unsplash('1502602898657-3e91760cbb34')),
  country(['gabao', 'gabon', 'ga'], ['Gabão', 'Gabon']),
  country(['gambia', 'gm'], ['Gâmbia', 'Gambia']),
  country(['gana', 'ghana', 'gh'], ['Gana', 'Ghana']),
  country(['georgia', 'ge'], ['Geórgia', 'Georgia']),
  country(['granada', 'grenada', 'gd'], ['Granada', 'Grenada']),
  country(['grecia', 'greece', 'gr'], ['Grécia', 'Greece'], unsplash('1555993539-1732b0258235')),
  country(['guatemala', 'gt'], ['Guatemala', 'Guatemala']),
  country(['guiana', 'guyana', 'gy'], ['Guiana', 'Guyana']),
  country(['guine', 'guinea', 'gn'], ['Guiné', 'Guinea']),
  country(['guine bissau', 'gw'], ['Guiné-Bissau', 'Guinea-Bissau']),
  country(['guine equatorial', 'equatorial guinea', 'gq'], ['Guiné Equatorial', 'Equatorial Guinea']),
  country(['haiti', 'ht'], ['Haiti', 'Haiti']),
  country(['honduras', 'hn'], ['Honduras', 'Honduras']),
  country(['hungria', 'hungary', 'hu'], ['Hungria', 'Hungary']),
  country(['iemen', 'yemen', 'ye'], ['Iêmen', 'Yemen']),
  country(['india', 'in'], ['Índia', 'India']),
  country(['indonesia', 'id'], ['Indonésia', 'Indonesia']),
  country(['ira', 'iran', 'ir'], ['Irão', 'Iran']),
  country(['iraque', 'iraq', 'iq'], ['Iraque', 'Iraq']),
  country(['irlanda', 'ireland', 'ie'], ['Irlanda', 'Ireland']),
  country(['islandia', 'iceland', 'is'], ['Islândia', 'Iceland']),
  country(['israel', 'il'], ['Israel', 'Israel']),
  country(['italia', 'italy', 'it'], ['Itália', 'Italy'], unsplash('1552832230-c0197dd311b5')),
  country(['jamaica', 'jm'], ['Jamaica', 'Jamaica']),
  country(['japao', 'japan', 'jp'], ['Japão', 'Japan'], unsplash('1542051841857-5f90071e7989')),
  country(['jordania', 'jordan', 'jo'], ['Jordânia', 'Jordan']),
  country(['kiribati', 'ki'], ['Kiribati']),
  country(['kuwait', 'kw'], ['Kuwait', 'Kuwait']),
  country(['laos', 'la'], ['Laos', 'Laos']),
  country(['lesoto', 'lesotho', 'ls'], ['Lesoto', 'Lesotho']),
  country(['letonia', 'latvia', 'lv'], ['Letônia', 'Latvia']),
  country(['libano', 'lebanon', 'lb'], ['Líbano', 'Lebanon']),
  country(['liberia', 'lr'], ['Libéria', 'Liberia']),
  country(['libia', 'libya', 'ly'], ['Líbia', 'Libya']),
  country(['liechtenstein', 'li'], ['Liechtenstein', 'Liechtenstein']),
  country(['lituania', 'lithuania', 'lt'], ['Lituânia', 'Lithuania']),
  country(['luxemburgo', 'luxembourg', 'lu'], ['Luxemburgo', 'Luxembourg']),
  country(['macedonia do norte', 'north macedonia', 'mk'], ['Macedônia do Norte', 'North Macedonia']),
  country(['madagascar', 'mg'], ['Madagascar', 'Madagascar']),
  country(['malasia', 'malaysia', 'my'], ['Malásia', 'Malaysia']),
  country(['malawi', 'mw'], ['Malawi', 'Malawi']),
  country(['maldivas', 'maldives', 'mv'], ['Maldivas', 'Maldives']),
  country(['mali', 'ml'], ['Mali', 'Mali']),
  country(['malta', 'mt'], ['Malta', 'Malta']),
  country(['marrocos', 'morocco', 'ma'], ['Marrocos', 'Morocco'], unsplash('1517824801-321778ff817e')),
  country(['mauricia', 'mauritius', 'mu'], ['Maurícia', 'Mauritius']),
  country(['mauritania', 'mr'], ['Mauritânia', 'Mauritania']),
  country(['mexico', 'mx'], ['México', 'Mexico'], unsplash('1510094456374-77f4762b3c24')),
  country(['mianmar', 'myanmar', 'burma', 'mm'], ['Mianmar', 'Myanmar']),
  country(['micronesia', 'fm'], ['Micronésia', 'Micronesia']),
  country(['mocambique', 'mozambique', 'mz'], ['Moçambique', 'Mozambique']),
  country(['moldavia', 'moldova', 'md'], ['Moldávia', 'Moldova']),
  country(['monaco', 'mc'], ['Mônaco', 'Monaco']),
  country(['mongolia', 'mn'], ['Mongólia', 'Mongolia']),
  country(['montenegro', 'me'], ['Montenegro', 'Montenegro']),
  country(['namibia', 'na'], ['Namíbia', 'Namibia']),
  country(['nauru', 'nr'], ['Nauru', 'Nauru']),
  country(['nepal', 'np'], ['Nepal', 'Nepal']),
  country(['nicaragua', 'ni'], ['Nicarágua', 'Nicaragua']),
  country(['niger', 'ne'], ['Níger', 'Niger']),
  country(['nigeria', 'ng'], ['Nigéria', 'Nigeria']),
  country(['noruega', 'norway', 'no'], ['Noruega', 'Norway']),
  country(['nova zelandia', 'new zealand', 'nz'], ['Nova Zelândia', 'New Zealand']),
  country(['oma', 'oman', 'om'], ['Omã', 'Oman']),
  country(['paises baixos', 'netherlands', 'holanda', 'nl'], ['Países Baixos', 'Netherlands'], unsplash('1534351590666-13e3e96b5017')),
  country(['palau', 'pw'], ['Palau', 'Palau']),
  country(['panama', 'pa'], ['Panamá', 'Panama']),
  country(['papua nova guine', 'papua new guinea', 'pg'], ['Papua-Nova Guiné', 'Papua New Guinea']),
  country(['paquistao', 'pakistan', 'pk'], ['Paquistão', 'Pakistan']),
  country(['paraguai', 'paraguay', 'py'], ['Paraguai', 'Paraguay'], unsplash('1542405996687-a8d9075e2b3b')),
  country(['peru', 'pe'], ['Peru', 'Peru'], unsplash('1526392060635-9d65b163cf6e')),
  country(['polonia', 'poland', 'pl'], ['Polônia', 'Poland']),
  country(['portugal', 'pt'], ['Portugal', 'Portugal'], unsplash('1555881400-74d7acaacd8b')),
  country(['quenia', 'kenya', 'ke'], ['Quênia', 'Kenya']),
  country(['quirguistao', 'kyrgyzstan', 'kg'], ['Quirguistão', 'Kyrgyzstan']),
  country(['reino unido', 'united kingdom', 'inglaterra', 'uk', 'gb'], ['Reino Unido', 'United Kingdom'], unsplash('1513635269975-59663e0ac1ad')),
  country(['republica centro africana', 'central african republic', 'cf'], ['República Centro-Africana', 'Central African Republic']),
  country(['republica dominicana', 'dominican republic', 'do'], ['República Dominicana', 'Dominican Republic']),
  country(['republica tcheca', 'czech republic', 'czechia', 'cz'], ['República Tcheca', 'Czech Republic'], unsplash('1541849543465-caf2a05f953b')),
  country(['romenia', 'romania', 'ro'], ['Romênia', 'Romania']),
  country(['ruanda', 'rwanda', 'rw'], ['Ruanda', 'Rwanda']),
  country(['russia', 'ru'], ['Rússia', 'Russia']),
  country(['samoa', 'ws'], ['Samoa', 'Samoa']),
  country(['san marino', 'sm'], ['San Marino', 'San Marino']),
  country(['sao cristovao e neves', 'saint kitts and nevis', 'kn'], ['São Cristóvão e Neves', 'Saint Kitts and Nevis']),
  country(['sao tome e principe', 'st'], ['São Tomé e Príncipe', 'São Tomé and Príncipe']),
  country(['sao vicente e granadinas', 'saint vincent and the grenadines', 'vc'], ['São Vicente e Granadinas', 'Saint Vincent and the Grenadines']),
  country(['seicheles', 'seychelles', 'sc'], ['Seicheles', 'Seychelles']),
  country(['senegal', 'sn'], ['Senegal', 'Senegal']),
  country(['serra leoa', 'sierra leone', 'sl'], ['Serra Leoa', 'Sierra Leone']),
  country(['servia', 'serbia', 'rs'], ['Sérvia', 'Serbia']),
  country(['singapura', 'singapore', 'sg'], ['Singapura', 'Singapore'], unsplash('1525626924213-d8914c2e1a52')),
  country(['siria', 'syria', 'sy'], ['Síria', 'Syria']),
  country(['somalia', 'so'], ['Somália', 'Somalia']),
  country(['sri lanka', 'lk'], ['Sri Lanka', 'Sri Lanka']),
  country(['suazilandia', 'eswatini', 'swaziland', 'sz'], ['Suazilândia', 'Eswatini']),
  country(['sudao do sul', 'south sudan', 'ss'], ['Sudão do Sul', 'South Sudan']),
  country(['sudao', 'sudan', 'sd'], ['Sudão', 'Sudan']),
  country(['suecia', 'sweden', 'se'], ['Suécia', 'Sweden']),
  country(['suica', 'switzerland', 'ch'], ['Suíça', 'Switzerland'], unsplash('1530122034175-a5e1e288bebb')),
  country(['suriname', 'sr'], ['Suriname', 'Suriname']),
  country(['tailandia', 'thailand', 'th'], ['Tailândia', 'Thailand'], unsplash('1552465011-b4e21bf8e59a')),
  country(['taiwan', 'tw'], ['Taiwan', 'Taiwan']),
  country(['tajiquistao', 'tajikistan', 'tj'], ['Tajiquistão', 'Tajikistan']),
  country(['tanzania', 'tz'], ['Tanzânia', 'Tanzania']),
  country(['timor leste', 'east timor', 'tl'], ['Timor-Leste', 'East Timor']),
  country(['togo', 'tg'], ['Togo', 'Togo']),
  country(['tonga', 'to'], ['Tonga', 'Tonga']),
  country(['trinidad e tobago', 'trinidad and tobago', 'tt'], ['Trinidad e Tobago', 'Trinidad and Tobago']),
  country(['tunisia', 'tn'], ['Tunísia', 'Tunisia']),
  country(['turcomenistao', 'turkmenistan', 'tm'], ['Turcomenistão', 'Turkmenistan']),
  country(['turquia', 'turkey', 'tr'], ['Turquia', 'Turkey'], unsplash('1524231757912-21f4fe3a7200')),
  country(['tuvalu', 'tv'], ['Tuvalu', 'Tuvalu']),
  country(['ucrania', 'ukraine', 'ua'], ['Ucrânia', 'Ukraine']),
  country(['uganda', 'ug'], ['Uganda', 'Uganda']),
  country(['uruguai', 'uruguay', 'uy'], ['Uruguai', 'Uruguay'], unsplash('1571019614246-ac5c128766b0')),
  country(['uzbequistao', 'uzbekistan', 'uz'], ['Uzbequistão', 'Uzbekistan']),
  country(['vanuatu', 'vu'], ['Vanuatu', 'Vanuatu']),
  country(['vaticano', 'vatican', 'va'], ['Vaticano', 'Vatican City']),
  country(['venezuela', 've'], ['Venezuela', 'Venezuela']),
  country(['vietna', 'vietnam', 'vn'], ['Vietnã', 'Vietnam']),
  country(['zambia', 'zm'], ['Zâmbia', 'Zambia']),
  country(['zimbabue', 'zimbabwe', 'zw'], ['Zimbábue', 'Zimbabwe']),
]
