module.exports = {
    testEnvironment: 'node',
    setupFiles: ['./tests/setup.js'],
    testMatch: ['**/tests/**/*.test.js'],
    clearMocks: true,
    restoreMocks: true,
    resetMocks: true,
    collectCoverageFrom: [
        'src/services/**/*.js',
        '!src/services/gamificationService.js',
        '!src/services/goalService.js',
        '!src/services/insightService.js',
        '!src/services/reportService.js',
        '!src/services/tripService.js',
        '!src/services/userService.js',
        '!src/services/googleCalendarSyncService.js',
        '!src/services/googleCalendarService.js',
        'src/utils/**/*.js',
        '!src/utils/logger.js',
        '!src/utils/helpers.js',
        'src/jobs/**/*.js',
        '!src/jobs/reminderSync.js',
        'src/middlewares/**/*.js',
        '!src/middlewares/rateLimitMiddleware.js',
    ],
    coverageDirectory: 'coverage',
    coverageThreshold: {
        global: {
            branches: 74,
            functions: 90,
            lines: 90,
            statements: 90,
        },
    },
};
