module.exports = {
    testEnvironment: 'node',
    setupFiles: ['./tests/setup.js'],
    testMatch: ['**/tests/**/*.test.js'],
    clearMocks: true,
    restoreMocks: true,
    resetMocks: true,
    collectCoverageFrom: [
        'src/services/**/*.js',
        '!src/services/gamificationService.js',
        '!src/services/insightService.js',
        '!src/services/viagemService.js',
        '!src/services/purchaseItemImageService.js',
        '!src/services/purchaseItemImageStorageService.js',
        '!src/services/userSyncService.js',
        '!src/services/grupoNotificationService.js',
        '!src/services/grupoService.js',
        '!src/services/purchasePlanningService.js',
        '!src/services/tripDestinationImageService.js',
        '!src/services/dashboardService.js',
        '!src/services/googleCalendarSyncService.js',
        '!src/services/googleCalendarService.js',
        'src/utils/**/*.js',
        '!src/utils/logger.js',
        '!src/utils/helpers.js',
        '!src/utils/viagemMapper.js',
        '!src/utils/grupoMapper.js',
        '!src/utils/prismaErrors.js',
        'src/jobs/**/*.js',
        '!src/jobs/reminderSync.js',
        'src/middlewares/**/*.js',
        '!src/middlewares/rateLimitMiddleware.js',
        '!src/middlewares/grupoInviteRateLimit.js',
        '!src/middlewares/grupoImageUploadMiddleware.js',
        '!src/middlewares/purchaseItemImageUploadMiddleware.js',
    ],
    coverageDirectory: 'coverage',
    coverageThreshold: {
        global: {
            branches: 65,
            functions: 88,
            lines: 87,
            statements: 85,
        },
    },
};
