const { GRUPO_BENEFICIO } = require('../constants/categoryBeneficioGroups');

/** Palavras-chave normalizadas (sem acento, minúsculas) — RF-159 importação. */
const KEYWORD_GROUPS = [
    // ── Alimentação (alta prioridade — refeições, lanches, bebidas no local) ──
    {
        id: 'alimentacao',
        tipos: ['DESPESA'],
        nomes: ['Alimentação', 'Alimentacao'],
        grupos: [GRUPO_BENEFICIO.ALIMENTACAO],
        suffixes: [
            'panificadora',
            'sorveteria',
            'confeitaria',
            'pizzaria',
            'hamburgueria',
            'lanchonete',
            'churrascaria',
            'acaiteria',
            'pastelaria',
            'tapiocaria',
            'creperia',
            'gelateria',
            'chocolateria',
            'cafeteria',
            'marmitaria',
            'espetaria',
            'rotisseria',
            'doceria',
            'peixaria',
            'galeteria',
            'boulangerie',
            'bistro',
            'cantina',
            'taberna',
            'choperia',
            'cervejaria',
            'empório',
            'emporio',
        ],
        keywords: [
            'alimentacao',
            'alimentício',
            'alimenticio',
            'refeicao',
            'refeição',
            'restaurante',
            'rest ',
            ' lanch',
            'padaria',
            'panificacao',
            'panificação',
            'confeito',
            'sorvete',
            'sorvetes',
            'gelato',
            'açai',
            'acai',
            'acaí',
            'pizza',
            'hamburguer',
            'hambúrguer',
            'burger',
            'hot dog',
            'cachorro quente',
            'sanduiche',
            'sanduíche',
            'sushi',
            'temaki',
            'poke',
            'ramen',
            'yakisoba',
            'comida',
            'food',
            'delivery',
            'ifood',
            'i food',
            'ubereats',
            'uber eats',
            'rappi',
            'zdelivery',
            'aiqfome',
            'ai qfome',
            'james delivery',
            'delivery much',
            '99 food',
            'fast food',
            'self service',
            'buffet',
            'marmita',
            'espetinho',
            'churrasco',
            'frango assado',
            'frango grelhado',
            'pastel',
            'tapioca',
            'crepe',
            'waffle',
            'bolo',
            'bolos',
            'doces',
            'confeitar',
            'café',
            'cafe',
            'coffee',
            'espresso',
            'starbucks',
            'suplicy',
            'havanna',
            'cacau show',
            'kopenhagen',
            'bar ',
            ' boteco',
            ' pub ',
            'choperia',
            'cervejaria',
            'bebidas',
            'adega',
            'vinicola',
            'vinícola',
            'acougue',
            'açougue',
            'acoug',
            'carnes',
            'delicatessen',
            'rotisserie',
            'gourmet',
            'snack',
            'lanche',
            'lanches',
            'cantina',
            'refeitorio',
            'refeitório',
            'food truck',
            'food hall',
            'praça de alimentacao',
            'praca de alimentacao',
            'mc donald',
            'mcdonalds',
            'mcdonald',
            'burger king',
            'subway',
            'kfc',
            'bobs',
            'giraffas',
            'spoleto',
            'china in box',
            'gendai',
            'outback',
            'applebee',
            'tgifridays',
            'tgi friday',
            'paris 6',
            'paris six',
            'coco bambu',
            'habib',
            'habibs',
            'ragazzo',
            'montana grill',
            'fogo de chao',
            'fogo de chão',
            'jeronimo',
            'the fifties',
            'mania de churrasco',
            'pizza hut',
            'dominos',
            'domino',
            'tele pizza',
            'patroni',
            'brasil pao',
            'brasil pão',
            'padaria paulista',
            'mr chen',
            'sukiya',
            'vivenda',
            'giraffas',
            'pernambucanas bar',
            'zero grau',
            'bacio di latte',
            'sukiya',
            'vivenda',
        ],
    },

    // ── Compras / mercado (supermercado, varejo, e-commerce) ──
    {
        id: 'compras',
        tipos: ['DESPESA'],
        nomes: ['Compras'],
        grupos: [GRUPO_BENEFICIO.COMPRAS],
        keywords: [
            'supermercado',
            'supermerc',
            'hipermerc',
            'hipermercado',
            'atacadao',
            'atacadão',
            'atacad',
            'assai',
            'carrefour',
            'pao de acucar',
            'pão de açúcar',
            'walmart',
            'makro',
            'sonda',
            'prezunic',
            'zona sul',
            'hortifruti',
            'nagumo',
            'savegnago',
            'savegnano',
            'mini mercado',
            'mini extra',
            'mercadinho',
            'mercado municipal',
            'sacolao',
            'sacolão',
            'feira livre',
            'feira ',
            'empório natural',
            'emporio natural',
            'natural da terra',
            'mundo verde',
            'amazon.com',
            'amazon br',
            'amazon marketplace',
            'amazon servicos',
            'amazon serviços',
            'mercado livre',
            'mercadolivre',
            'magalu',
            'magazine luiza',
            'americanas',
            'ame digital',
            'submarino',
            'shopee',
            'shein',
            'aliexpress',
            'ali express',
            'renner',
            'c&a',
            'riachuelo',
            'marisa',
            'centauro',
            'decathlon',
            'nike',
            'adidas',
            'puma',
            'zara',
            'hm ',
            'h&m',
            'leroy merlin',
            'casas bahia',
            'ponto frio',
            'fast shop',
            'polishop',
            'shopping',
            ' loja ',
            'lojas ',
            'ecommerce',
            'e-commerce',
            'marketplace',
            'varejo',
            'departamento',
            'utilidades',
            'presentes e',
        ],
    },

    // ── Transporte ──
    {
        id: 'transporte',
        tipos: ['DESPESA'],
        nomes: ['Transporte'],
        grupos: [GRUPO_BENEFICIO.TRANSPORTE],
        keywords: [
            'uber',
            '99pop',
            '99 pop',
            '99 taxi',
            '99app',
            'cabify',
            'indriver',
            'in driver',
            'taxi',
            'táxi',
            'metro',
            'metrô',
            'cptm',
            'via mobilidade',
            'bilhete unico',
            'bilhete único',
            'onibus',
            'ônibus',
            'bus ',
            'integracao',
            'integração',
            'estaciona',
            'estapar',
            'zul park',
            'zul',
            'park ',
            'estacionamento',
            'pedagio',
            'pedágio',
            'sem parar',
            'conectcar',
            'veloe',
            'move mais',
            'autoban',
            'posto',
            'ipiranga',
            'shell',
            'petrobras',
            'br distribuidora',
            'ale combust',
            'combustivel',
            'combustível',
            'gasolina',
            'etanol',
            'abastece',
            'auto posto',
            'locadora',
            'localiza',
            'movida',
            'unidas',
            'mobi',
            'bike ',
            'tembici',
            'itau bike',
            'grin',
            'patinete',
            'lime',
        ],
        exclude: ['uber eats', 'ubereats'],
    },

    // ── Saúde ──
    {
        id: 'saude',
        tipos: ['DESPESA'],
        nomes: ['Saúde', 'Saude'],
        keywords: [
            'farmacia',
            'farmácia',
            'droga raia',
            'drogasil',
            'drogal',
            'pacheco',
            'ultrafarma',
            'panvel',
            'extrafarma',
            'drog sao paulo',
            'drogarias sao paulo',
            'drogarias',
            'manipulacao',
            'manipulação',
            'laboratorio',
            'laboratório',
            'laborator',
            'clinica',
            'clínica',
            'hospital',
            'consultorio',
            'consultório',
            'dentista',
            'odontolog',
            'ortodont',
            'fisioterap',
            'psicolog',
            'medico',
            'médico',
            'exame',
            'vacina',
            'unimed',
            'amil',
            'sulamerica',
            'sulamérica',
            'bradesco saude',
            'bradesco saúde',
            'notredame',
            'notre dame',
            'hapvida',
            'prevent senior',
            'optica',
            'óptica',
            'otica',
            'ótica',
            'lens',
            'lentes',
        ],
    },

    // ── Beleza ──
    {
        id: 'beleza',
        tipos: ['DESPESA'],
        nomes: ['Beleza'],
        keywords: [
            'salao',
            'salão',
            'barbearia',
            'barber',
            'cabeleir',
            'manicure',
            'pedicure',
            'nail',
            'unhas',
            'estetica',
            'estética',
            'spa ',
            'depilacao',
            'depilação',
            'perfumaria',
            'sephora',
            'boticario',
            'boticário',
            'natura ',
            'avon ',
            'eudora',
            'quem disse berenice',
            'qdb',
            'mac cosmetic',
            'makeup',
            'maquiagem',
        ],
    },

    // ── Vestuário ──
    {
        id: 'vestuario',
        tipos: ['DESPESA'],
        nomes: ['Vestuário', 'Vestuario'],
        keywords: [
            'vestuario',
            'vestuário',
            'moda',
            'confec',
            'confecção',
            'calcado',
            'calçado',
            'sapataria',
            'sapato',
            'tenis',
            'tênis',
            'roupa',
            'camisaria',
            'lingerie',
            'hering',
            'reserva',
            'le lis',
            'animale',
            'farm ',
            'shoulder',
            'arezzo',
            'schutz',
            'melissa',
            'havaianas',
        ],
    },

    // ── Tecnologia ──
    {
        id: 'tecnologia',
        tipos: ['DESPESA'],
        nomes: ['Tecnologia'],
        keywords: [
            'apple store',
            'apple.com',
            'samsung',
            'xiaomi',
            'motorola',
            'dell ',
            'lenovo',
            'hp ',
            'acer',
            'kabum',
            'pichau',
            'terabyte',
            'chip art',
            'informatica',
            'informática',
            'celular',
            'smartphone',
            'iphone',
            'playstation',
            'xbox',
            'nintendo',
            'steam',
            'epic games',
            'google play',
            'app store',
            'icloud',
            'hostinger',
            'godaddy',
            'github',
            'digital ocean',
            'aws ',
            'azure',
            'cloudflare',
        ],
    },

    // ── Moradia / contas ──
    {
        id: 'moradia',
        tipos: ['DESPESA'],
        nomes: ['Moradia'],
        keywords: [
            'aluguel',
            'condominio',
            'condomínio',
            'iptu',
            'imobiliaria',
            'imobiliária',
            'incorporadora',
            'administradora',
            'locacao',
            'locação',
            'fiador',
            'seguro resid',
        ],
    },
    {
        id: 'moradia_utilities',
        tipos: ['DESPESA'],
        nomes: ['Moradia', 'Serviços e Assinaturas'],
        keywords: [
            'energia',
            'cpfl',
            'enel',
            'light',
            'cemig',
            'copel',
            'equatorial',
            'neoenergia',
            'eletropaulo',
            'conta de luz',
            'sabesp',
            'copasa',
            'caesb',
            'cedae',
            'agua e esgoto',
            'água e esgoto',
            'conta de agua',
            'conta de água',
            'comgas',
            'gas natural',
            'gás natural',
            'ultragaz',
            'supergasbras',
        ],
    },
    {
        id: 'servicos_assinaturas',
        tipos: ['DESPESA'],
        nomes: ['Serviços e Assinaturas'],
        keywords: [
            'vivo',
            'claro',
            'tim ',
            ' oi ',
            'oi fibra',
            'internet',
            'banda larga',
            'telefon',
            'netflix',
            'spotify',
            'amazon prime',
            'disney',
            'disney+',
            'hbo',
            'max ',
            'globoplay',
            'deezer',
            'youtube premium',
            'google storage',
            'google one',
            'microsoft 365',
            'office 365',
            'adobe',
            'canva',
            'notion',
            'linkedin premium',
            'assinatura',
            'mensalidade',
            'plano ',
            'academia',
            'smart fit',
            'bluefit',
            'bodytech',
            'selfit',
            'fitness',
            'gym ',
            'crossfit',
        ],
    },

    // ── Lazer ──
    {
        id: 'lazer',
        tipos: ['DESPESA'],
        nomes: ['Lazer'],
        keywords: [
            'cinema',
            'cinemark',
            'kinoplex',
            'uci',
            'ingresso',
            'ingresso.com',
            'eventim',
            'sympla',
            'ticketmaster',
            'teatro',
            'show',
            'parque',
            'museu',
            'zoologico',
            'zoológico',
            'aquario',
            'aquário',
            'bet ',
            'aposta',
            'jogo',
            'game',
            'twitch',
            'prime gaming',
            'clube',
            'futebol',
            'estadio',
            'estádio',
            'match',
            'partida',
        ],
    },

    // ── Educação ──
    {
        id: 'educacao',
        tipos: ['DESPESA'],
        nomes: ['Educação', 'Educacao'],
        keywords: [
            'escola',
            'colegio',
            'colégio',
            'faculdade',
            'universidade',
            'uni ',
            ' curso',
            'cursinho',
            'udemy',
            'alura',
            'rocketseat',
            'descomplica',
            'mensalidade escolar',
            'material escolar',
            'livro',
            'livraria',
            'saraiva',
            'cultura',
            'amazon kindle',
            'duolingo',
            'ingles',
            'inglês',
            'idioma',
        ],
    },

    // ── Pet ──
    {
        id: 'pet',
        tipos: ['DESPESA'],
        nomes: ['Pet'],
        keywords: [
            'petz',
            'cobasi',
            'pet shop',
            'petshop',
            'pet love',
            'petlove',
            'veterin',
            'vet ',
            'clinica vet',
            'racao',
            'ração',
            'pet center',
        ],
    },

    // ── Viagem ──
    {
        id: 'viagem',
        tipos: ['DESPESA'],
        nomes: ['Viagem'],
        keywords: [
            'hotel',
            'pousada',
            'hostel',
            'airbnb',
            'booking',
            'decolar',
            '123milhas',
            'maxmilhas',
            'latam',
            'gol ',
            'gol linhas',
            'azul linhas',
            'cvc',
            'viajanet',
            'passagem',
            'aereo',
            'aéreo',
            'aeroporto',
            'tam ',
            'emirates',
            'hostelworld',
            'trip ',
            'viagem',
            'turismo',
            'agencia de viagem',
            'agência de viagem',
        ],
    },

    // ── Veículos ──
    {
        id: 'veiculos',
        tipos: ['DESPESA'],
        nomes: ['Veículos', 'Veiculos', 'Transporte'],
        keywords: [
            'oficina',
            'mecanica',
            'mecânica',
            'auto center',
            'autocenter',
            'pneu',
            'pneus',
            'borracharia',
            'lavagem',
            'lava jato',
            'lava rapido',
            'lava rápido',
            'ipva',
            'detran',
            'licenciamento',
            'seguro auto',
            'porto seguro auto',
            'tokio marine',
            'revenda',
            'concessionaria',
            'concessionária',
            'troca de oleo',
            'troca de óleo',
        ],
    },

    // ── Finanças / taxas ──
    {
        id: 'financas',
        tipos: ['DESPESA'],
        nomes: ['Finanças', 'Financas'],
        keywords: [
            'tarifa',
            'taxa',
            'iof',
            'juros',
            'anuidade',
            'cartao',
            'cartão',
            'emprestimo',
            'empréstimo',
            'financiamento',
            'parcela',
            'consorcio',
            'consórcio',
            'banco',
            'boleto',
            'encargo',
            'multa',
            'juro',
            'cet ',
        ],
    },

    // ── Trabalho ──
    {
        id: 'trabalho',
        tipos: ['DESPESA'],
        nomes: ['Trabalho'],
        keywords: [
            'coworking',
            'wework',
            'material de escritorio',
            'material de escritório',
            'papelaria',
            'kalunga',
            'le postiche',
            'correios',
            'sedex',
            'malote',
            'frete',
            'logistica',
            'logística',
        ],
    },

    // ── Família / presentes ──
    {
        id: 'familia',
        tipos: ['DESPESA'],
        nomes: ['Família', 'Familia', 'Presentes'],
        keywords: [
            'presente',
            'gift',
            'floricultura',
            'flores',
            'brinquedo',
            'ri happy',
            'pbkids',
            'baby',
            'bebe',
            'bebê',
            'infantil',
            'fraldas',
            'pampers',
            'huggies',
        ],
    },

    // ── RECEITAS ──
    {
        id: 'receita_salario',
        tipos: ['RECEITA'],
        nomes: ['Salário', 'Salario'],
        keywords: [
            'salario',
            'salário',
            'provento',
            'pagamento folha',
            'folha pagamento',
            'holerite',
            'adiantamento',
            'credito salario',
            'crédito salario',
            'credito salário',
            'crédito salário',
            'remuneracao',
            'remuneração',
            'ordenado',
            'vencimento',
            'beneficio salarial',
            'benefício salarial',
        ],
    },
    {
        id: 'receita_transferencia',
        tipos: ['RECEITA'],
        nomes: ['Salário', 'Salario', 'Freelance', 'Extra'],
        keywords: [
            'pix receb',
            'pix - receb',
            'transferencia receb',
            'transferência receb',
            'ted receb',
            'doc receb',
            'deposito',
            'depósito',
            'credito em conta',
            'crédito em conta',
            'credito conta',
            'crédito conta',
            'transf receb',
        ],
    },
    {
        id: 'receita_investimentos',
        tipos: ['RECEITA'],
        nomes: ['Investimentos', 'Renda', 'Extra'],
        keywords: [
            'rendimento',
            'juros',
            'dividendo',
            'cupom',
            'fii',
            'tesouro',
            'resgate',
            'cdb',
            'lci',
            'lca',
            'poupanca',
            'poupança',
            'corretora',
            'xp invest',
            'clear corretora',
            'rico invest',
            'inter invest',
            'nu invest',
            'binance',
            'coinbase',
        ],
    },
    {
        id: 'receita_outras',
        tipos: ['RECEITA'],
        nomes: ['Freelance', 'Extra', 'Salário', 'Salario'],
        keywords: [
            'recarga',
            'disponibiliz',
            'saldo liberado',
            'liberacao',
            'liberação',
            'credito benef',
            'crédito benef',
            'estorno',
            'devolucao',
            'devolução',
            'reembolso',
            'cashback',
            'freela',
            'freelance',
            'bico',
            'consultoria',
            'honorario',
            'honorário',
            'nota fiscal',
            'nf-e',
            'nfe',
            'pagamento receb',
        ],
    },
];

module.exports = { KEYWORD_GROUPS };
